#普通数据的配置
name: zhangsan
#addr: 北京
#server:
# port:8081

#对象的配置,层级关系
person: 
 name: zhangsan
 age: 18
 addr: beijing
 
#行内对象配置
#person: {name: zhangan,age: 18,addr: beijing}

#配置数据，集合(普通字符串)
#city:
# - beijing
# - tianjing
# - chongqin
# - shanghai

#行内配置数据，集合(普通字符串)
#city: [beijing,tianjing,chongqin,shanghai]

#配置数据，集合(对象数据)
#person: 
# - name: zhangsi
#   age: 18
#   addr: beijing
# - name: zhangsan
#   age: 17
#   addr: tianjing 

#行内配置数据，集合(对象数据)
#person: [{name: zhangsan,age: 18,addr: beijing},{name: zhangsi,age: 17,addr: tianjing}]

#map配置
#map: 
# key1: value1
# key2: value2















